#MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intranet
    username: jorge
    password: jorge
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
